---
# Variable configuration.
- name: Include OS-specific variables (Debian).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

- name: Include OS-specific variables (RedHat).
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'RedHat'

- name: Define apt gpg key.
  set_fact:
    apt_gpg_key_url: "{{ __apt_gpg_key_url }}"
  when:
    - apt_gpg_key_url is not defined
    - __apt_gpg_key_url is defined

- name: Define postgresql_repo.
  set_fact:
    postgresql_repository_url: "{{ __postgresql_repository_url }}"
  when: postgresql_repository_url is not defined

- name: Define postgresql_packages.
  set_fact:
    postgresql_packages: "{{ __postgresql_packages | list }}"
  when: postgresql_packages is not defined
