---
- name: Converge
  hosts: all
  become: true
  vars:
    - ansible_python_interpreter: /usr/bin/python
    - pip_install_packages: [psycopg2]
  roles:
    - role: chauanhtuandl.repo_epel
    - role: chauanhtuandl.pip
    - role: chauanhtuandl.postgresql-migration
